# Generated by Django 5.0.4 on 2025-07-07 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmsRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minValue', models.FloatField()),
                ('maxValue', models.FloatField()),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmsRange', to='dynamic.measurements')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarmsRange', to='dynamic.meters')),
            ],
        ),
    ]
