# Generated by Django 5.0.4 on 2025-07-07 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('alarmType', models.CharField(max_length=100)),
                ('acknowledged', models.BooleanField(default=False)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='dynamic.measurements')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='dynamic.meters')),
            ],
        ),
    ]
