# Generated by Django 5.0.4 on 2025-07-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0002_alarms'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarms',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
