# Generated by Django 5.0.4 on 2025-07-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_alarms_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsrange',
            name='maxValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alarmsrange',
            name='minValue',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
