# Generated by Django 5.0.4 on 2025-09-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Masters',
            new_name='MotorMasters',
        ),
    ]
