# Generated by Django 5.0.4 on 2025-09-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0003_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='temperature',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
