# Generated by Django 5.0.4 on 2025-09-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0004_motor_temperature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motor',
        ),
    ]
