# Generated by Django 5.0.4 on 2025-09-11 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_masters'),
        ('scada', '0006_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorArea', to='dynamic.areas'),
        ),
    ]
