# Generated by Django 5.0.4 on 2025-09-11 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0007_alter_motor_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Motor',
        ),
    ]
