# Generated by Django 5.0.4 on 2025-09-11 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_masters'),
        ('scada', '0008_delete_motor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorName', models.CharField(max_length=100)),
                ('rpm', models.FloatField()),
                ('totalRunHour', models.FloatField()),
                ('temperature', models.FloatField()),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motorBuilding', to='dynamic.buildings')),
                ('motorMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='scada.motormasters')),
            ],
        ),
    ]
