# Generated by Django 5.0.4 on 2025-09-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0009_motor'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='dbNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motor',
            name='fields',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='ip',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
