# Generated by Django 5.0.4 on 2025-09-13 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0010_motor_dbno_motor_fields_motor_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='motorMaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='scada.motormasters'),
        ),
    ]
