# Generated by Django 5.0.4 on 2025-09-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0011_alter_motor_motormaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motor',
            name='rpm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='totalRunHour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
