# Generated by Django 5.0.4 on 2025-09-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0012_alter_motor_rpm_alter_motor_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='isOn',
            field=models.BooleanField(default=False),
        ),
    ]
