# Generated by Django 5.0.4 on 2025-09-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0013_motor_ison'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motor',
            name='rpm',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='motor',
            name='totalRunHour',
        ),
    ]
