# Generated by Django 5.0.4 on 2025-09-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0014_remove_motor_rpm_remove_motor_temperature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='endByte',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motor',
            name='rack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motor',
            name='slot',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='motor',
            name='startByte',
            field=models.IntegerField(default=0),
        ),
    ]
