# Generated by Django 5.0.4 on 2025-09-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0015_motor_endbyte_motor_rack_motor_slot_motor_startbyte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motor',
            old_name='endByte',
            new_name='dataSize',
        ),
    ]
