# Generated by Django 5.0.4 on 2025-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0016_rename_endbyte_motor_datasize'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='motorOffOffset',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motor',
            name='motorOnOffset',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
