# Generated by Django 5.0.4 on 2025-09-15 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0017_motor_motoroffoffset_motor_motoronoffset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highByte', models.IntegerField()),
                ('lowByte', models.IntegerField()),
                ('highBit', models.IntegerField()),
                ('lowBit', models.IntegerField()),
                ('valueByte', models.IntegerField()),
                ('valueBit', models.IntegerField()),
                ('motor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='motors', to='scada.motor')),
            ],
        ),
    ]
