# Generated by Django 5.0.4 on 2025-09-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0018_tank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='motor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tank', to='scada.motor'),
        ),
    ]
