# Generated by Django 5.0.4 on 2025-09-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0019_alter_tank_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='highBit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='highByte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='lowBit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='lowByte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='valueBit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='valueByte',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
