# Generated by Django 5.0.4 on 2025-09-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0020_alter_tank_highbit_alter_tank_highbyte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tankVolume',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
