# Generated by Django 5.0.4 on 2025-09-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0021_tank_tankvolume'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='runFeedbackOffset',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
