# Generated by Django 5.0.4 on 2025-09-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0022_motor_runfeedbackoffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='motor',
            name='tripOffset',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
