# Generated by Django 5.0.4 on 2025-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scada', '0023_motor_tripoffset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='tankName',
            field=models.CharField(blank=True, default=True, max_length=100, null=True),
        ),
    ]
