# Generated by Django 5.2.1 on 2025-09-03 12:52

import django.db.models.deletion
import report.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_alter_usermodel_name_alter_usermodel_profilepic_and_more'),
        ('dynamic', '0015_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fixed_charge', models.DecimalField(blank=True, decimal_places=4, default=0.0, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('date_range_start', models.DateField(blank=True, null=True)),
                ('date_range_end', models.DateField(blank=True, null=True)),
                ('date_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('remarks', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('total_consumption', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('extra_fields', models.JSONField()),
                ('generatedBy', models.ForeignKey(blank=True, default=report.models.get_default_user, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usermodel')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dynamic.meters')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(upload_to='media/reportImages')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dynamic.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='ReportDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_type', models.CharField(max_length=50)),
                ('date_range_start', models.DateTimeField(blank=True, null=True)),
                ('date_range_end', models.DateTimeField(blank=True, null=True)),
                ('period_type', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(default='', max_length=1000)),
                ('image', models.ImageField(upload_to='media/reportImages/')),
                ('measurements', models.ManyToManyField(blank=True, to='dynamic.measurements')),
                ('meters', models.ManyToManyField(blank=True, to='dynamic.meters')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dynamic.site')),
                ('report_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='report.reportformat')),
            ],
        ),
    ]
