# Generated by Django 5.2.1 on 2025-09-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
