# Generated by Django 5.2.1 on 2025-07-14 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='report',
            name='format',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='report',
        ),
        migrations.RemoveField(
            model_name='reportrun',
            name='generated_by',
        ),
        migrations.DeleteModel(
            name='ReportFormat',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='ReportRun',
        ),
    ]
