# Generated by Django 5.2.1 on 2025-07-14 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
        ('report', '0002_remove_report_created_by_remove_report_format_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_type', models.CharField(max_length=50)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('period_type', models.CharField(max_length=20)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.measurements')),
                ('meters', models.ManyToManyField(to='dynamic.meters')),
                ('report_format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='report.reportformat')),
            ],
        ),
    ]
