# Generated by Django 5.2.1 on 2025-09-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_billing_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='authority',
            field=models.CharField(default='', max_length=100),
        ),
    ]
