# Generated by Django 5.2.1 on 2025-07-14 06:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportformat',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
