# Generated by Django 5.0.4 on 2025-09-07 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0015_alter_site_latitude_alter_site_longitude'),
        ('report', '0004_alter_reportdiagram_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdiagram',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.site'),
        ),
    ]
