# Generated by Django 5.2.1 on 2025-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
        ('report', '0004_reportformat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdiagram',
            name='measurement',
        ),
        migrations.AddField(
            model_name='reportdiagram',
            name='measurements',
            field=models.ManyToManyField(blank=True, to='dynamic.measurements'),
        ),
        migrations.AlterField(
            model_name='reportdiagram',
            name='date_range_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdiagram',
            name='date_range_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdiagram',
            name='meters',
            field=models.ManyToManyField(blank=True, to='dynamic.meters'),
        ),
        migrations.AlterField(
            model_name='reportdiagram',
            name='period_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
