# Generated by Django 5.2.1 on 2025-07-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_remove_reportdiagram_measurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdiagram',
            name='date_range_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportdiagram',
            name='date_range_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
