# Generated by Django 5.2.1 on 2025-07-15 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
        ('report', '0006_alter_reportdiagram_date_range_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdiagram',
            name='site',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='dynamic.site'),
        ),
    ]
