# Generated by Django 5.2.1 on 2025-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_reportdiagram_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdiagram',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
