# Generated by Django 5.2.1 on 2025-07-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_reportformat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdiagram',
            name='image',
            field=models.ImageField(default='', upload_to='media/reportImages'),
        ),
    ]
