# Generated by Django 5.2.1 on 2025-07-17 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermodel_last_activity'),
        ('report', '0010_reportdiagram_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportdiagram',
            name='image',
            field=models.ImageField(upload_to='media/reportImages/'),
        ),
        migrations.AlterField(
            model_name='reportformat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.usermodel'),
        ),
    ]
