# Generated by Django 5.2.1 on 2025-07-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0011_alter_reportdiagram_image_alter_reportformat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportformat',
            name='logo',
            field=models.ImageField(default='', upload_to='media/reportImages'),
            preserve_default=False,
        ),
    ]
