# Generated by Django 5.2.1 on 2025-07-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0014_meters_ecological'),
        ('report', '0011_alter_reportdiagram_image_alter_reportformat_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportformat',
            name='logo',
            field=models.ImageField(default=7, upload_to='media/reportImages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportformat',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.site'),
        ),
    ]
