# Generated by Django 5.2.1 on 2025-07-23 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0014_meters_ecological'),
        ('report', '0012_reportformat_logo_reportformat_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportformat',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dynamic.site'),
        ),
    ]
