# Generated by Django 5.2.1 on 2025-06-16 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard', to='dynamic.site')),
            ],
        ),
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('gadget_type', models.CharField(default='', max_length=100)),
                ('dashboard', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='dashboard.dashboard')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='dynamic.measurements')),
                ('meters', models.ManyToManyField(default='', related_name='gadgets', to='dynamic.meters')),
            ],
        ),
    ]
