# Generated by Django 5.2.1 on 2025-06-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gadgets',
        ),
    ]
