# Generated by Django 5.2.1 on 2025-06-16 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_gadgets'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gadget_type', models.CharField(max_length=100)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='dashboard.dashboard')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='dynamic.measurements')),
                ('meters', models.ManyToManyField(related_name='gadgets', to='dynamic.meters')),
            ],
        ),
    ]
