# Generated by Django 5.0.4 on 2025-06-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_files'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gadgets',
            name='measurement',
        ),
        migrations.AddField(
            model_name='gadgets',
            name='measurement',
            field=models.ManyToManyField(related_name='gadgets', to='dynamic.measurements'),
        ),
    ]
