# Generated by Django 5.2.1 on 2025-06-23 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_gadgets_measurement_gadgets_measurement'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='dynamic.meters')),
            ],
        ),
    ]
