# Generated by Django 5.0.4 on 2025-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_meterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
