# Generated by Django 5.0.4 on 2025-06-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_meterreading_timestamp'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatestMeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data', models.JSONField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataLatest', to='dynamic.meters')),
            ],
        ),
    ]
