# Generated by Django 5.0.4 on 2025-06-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_latestmeterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestmeterreading',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
