# Generated by Django 5.0.4 on 2025-06-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_latestmeterreading_timestamp_and_more'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReadingAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3monthly', '3Monthly'), ('6monthly', '6Monthly'), ('yearly', 'Yearly')], max_length=20)),
                ('start_date', models.DateField()),
                ('average_value', models.FloatField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.meters')),
            ],
            options={
                'unique_together': {('meter', 'measurement', 'period_type', 'start_date')},
            },
        ),
    ]
