# Generated by Django 5.0.4 on 2025-06-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_meterreadingaggregate'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meterreadingaggregate',
            unique_together={('meter', 'period_type', 'start_date')},
        ),
        migrations.AddField(
            model_name='meterreadingaggregate',
            name='aggregateData',
            field=models.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='meter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dynamic.meters'),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='period_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3monthly', '3Monthly'), ('6monthly', '6Monthly'), ('yearly', 'Yearly')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='start_date',
            field=models.DateField(default=''),
        ),
        migrations.RemoveField(
            model_name='meterreadingaggregate',
            name='average_value',
        ),
        migrations.RemoveField(
            model_name='meterreadingaggregate',
            name='measurement',
        ),
    ]
