# Generated by Django 5.2.1 on 2025-06-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_meterreadingaggregate_unique_together_and_more'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meterreadingaggregate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='aggregateData',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.meters'),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='period_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('3monthly', '3Monthly'), ('6monthly', '6Monthly'), ('yearly', 'Yearly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meterreadingaggregate',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='hierarchyDataAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.site')),
            ],
        ),
    ]
