# Generated by Django 5.2.1 on 2025-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_meterreadingaggregate_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hierarchyDataAggregate',
        ),
    ]
