# Generated by Django 5.2.1 on 2025-06-28 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_delete_hierarchydataaggregate'),
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.CreateModel(
            name='HierarchyDataAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('data', models.JSONField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.site')),
            ],
        ),
    ]
