# Generated by Django 5.2.1 on 2025-07-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_hierarchydataaggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgets',
            name='access',
            field=models.CharField(default='', max_length=100),
        ),
    ]
