# Generated by Django 5.2.1 on 2025-07-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_gadgets_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='access',
            field=models.JSONField(),
        ),
    ]
