# Generated by Django 5.2.1 on 2025-07-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_gadgets_access'),
        ('dynamic', '0014_meters_ecological'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hierarchydataaggregate',
            unique_together={('site', 'period_type', 'start_date')},
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['meter', 'timestamp'], name='dashboard_m_meter_i_a92531_idx'),
        ),
    ]
