# Generated by Django 5.0.4 on 2025-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_hierarchydataaggregate_unique_together_and_more'),
        ('dynamic', '0014_meters_ecological'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='latestmeterreading',
            index=models.Index(fields=['meter', 'timestamp'], name='dashboard_l_meter_i_eef1ed_idx'),
        ),
    ]
