# Generated by Django 5.0.4 on 2025-07-31 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_centraldashboard_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CentralDashboard',
        ),
    ]
