# Generated by Django 5.0.4 on 2025-09-08 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_delete_centraldashboard'),
        ('dynamic', '0016_areas_image_buildings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gadgets',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.areas'),
        ),
        migrations.AddField(
            model_name='gadgets',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dynamic.buildings'),
        ),
    ]
