# Generated by Django 5.0.4 on 2025-09-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_gadgets_area_gadgets_building'),
        ('dynamic', '0016_areas_image_buildings_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gadgets',
            name='meters',
            field=models.ManyToManyField(blank=True, null=True, related_name='gadgets', to='dynamic.meters'),
        ),
    ]
