# Generated by Django 5.0.4 on 2025-07-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='profilePic',
            field=models.ImageField(default='', upload_to='media/images'),
            preserve_default=False,
        ),
    ]
