# Generated by Django 5.2.1 on 2025-07-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginhistory_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
