# Generated by Django 5.2.1 on 2025-07-19 08:25

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_usermodel_site'),
        ('dynamic', '0011_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='site',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='dynamic.site'),
        ),
    ]
