# Generated by Django 5.2.1 on 2025-07-20 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usermodel_site'),
        ('dynamic', '0012_measurements_ecological'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamic.site'),
        ),
    ]
