# Generated by Django 5.2.1 on 2025-07-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCongifguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.BooleanField(default=True)),
                ('dashboard', models.BooleanField(default=True)),
                ('alarm', models.BooleanField(default=True)),
                ('siteLocations', models.BooleanField(default=True)),
                ('subscribed', models.BooleanField(default=True)),
            ],
        ),
    ]
