# Generated by Django 5.2.1 on 2025-07-24 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GlobalCongifguration',
            new_name='GlobalConfiguration',
        ),
    ]
