# Generated by Django 5.0.4 on 2025-09-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_globalcongifguration_globalconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='scada',
            field=models.BooleanField(default=False),
        ),
    ]
