# Generated by Django 5.0.4 on 2025-09-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_globalconfiguration_scada'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='billing',
            field=models.BooleanField(default=True),
        ),
    ]
