# Generated by Django 5.0.4 on 2025-10-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_globalconfiguration_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='treeType',
            field=models.CharField(default='hierarchy', max_length=100),
        ),
    ]
