# Generated by Django 5.2.4 on 2026-01-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_globalconfiguration_treetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='dataLake',
            field=models.BooleanField(default=False),
        ),
    ]
