# Generated by Django 5.2.4 on 2026-02-01 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_globalconfiguration_datalake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalconfiguration',
            name='dataLake',
        ),
    ]
