# Generated by Django 5.2.1 on 2025-06-14 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='meterType',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='areas',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='dynamic.buildings'),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='dynamic.site'),
        ),
        migrations.AlterField(
            model_name='gadgets',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to='dynamic.meters'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.areas'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='ip',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meters',
            name='loadType',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.loadtype'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
