# Generated by Django 5.2.1 on 2025-06-15 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0002_meters_metertype_alter_areas_building_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.areas'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='ip',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meters',
            name='loadType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.loadtype'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='meterType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='meters',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
