# Generated by Django 5.2.1 on 2025-06-15 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0003_alter_meters_area_alter_meters_ip_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gadgets',
        ),
    ]
