# Generated by Django 5.2.1 on 2025-06-15 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0004_delete_gadgets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dynamic.meters')),
            ],
        ),
    ]
