# Generated by Django 5.2.1 on 2025-06-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0005_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='meterType',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
