# Generated by Django 5.2.1 on 2025-06-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0007_alter_measurements_metertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='meterType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
