# Generated by Django 5.0.4 on 2025-07-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0008_alter_measurements_metertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meters',
            name='low',
            field=models.FloatField(default=0),
        ),
    ]
