# Generated by Django 5.0.4 on 2025-07-07 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0009_meters_high_meters_low'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meters',
            name='high',
        ),
        migrations.RemoveField(
            model_name='meters',
            name='low',
        ),
    ]
