# Generated by Django 5.2.1 on 2025-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0010_remove_meters_high_remove_meters_low'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
