# Generated by Django 5.2.1 on 2025-07-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0011_site_latitude_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurements',
            name='ecological',
            field=models.BooleanField(default=False),
        ),
    ]
