# Generated by Django 5.2.1 on 2025-07-20 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0012_measurements_ecological'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurements',
            name='ecological',
        ),
    ]
