# Generated by Django 5.2.1 on 2025-07-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0013_remove_measurements_ecological'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='ecological',
            field=models.BooleanField(default=False),
        ),
    ]
