# Generated by Django 5.0.4 on 2025-07-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0014_meters_ecological'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.CharField(max_length=1000),
        ),
    ]
