# Generated by Django 5.0.4 on 2025-09-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0015_alter_site_latitude_alter_site_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='areas',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/areaImages'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/buildingImages'),
        ),
    ]
