# Generated by Django 5.0.4 on 2025-09-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0017_masters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Masters',
        ),
    ]
