# Generated by Django 5.0.4 on 2025-10-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0019_masters'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='registerMapping',
            field=models.JSONField(default={}),
        ),
    ]
