# Generated by Django 5.0.4 on 2025-10-07 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0020_meters_registermapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='registerMapping',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
