# Generated by Django 5.0.4 on 2025-10-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0021_alter_meters_registermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='unit_id',
            field=models.IntegerField(default=1),
        ),
    ]
