# Generated by Django 5.0.4 on 2025-10-09 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0023_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='meter',
            new_name='measurement',
        ),
    ]
