# Generated by Django 5.0.4 on 2025-10-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0024_rename_meter_units_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='measurement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='dynamic.measurements'),
        ),
    ]
