# Generated by Django 5.0.4 on 2025-10-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0025_alter_units_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurements',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='dynamic.meters'),
        ),
    ]
