# Generated by Django 5.2.4 on 2026-01-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0026_alter_measurements_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='meters',
            name='isScada',
            field=models.BooleanField(default=False),
        ),
    ]
