# Generated by Django 5.2.4 on 2026-01-07 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic', '0027_meters_isscada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meters',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.areas'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meters',
            name='loadType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='dynamic.loadtype'),
        ),
        migrations.AlterField(
            model_name='meters',
            name='meterType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meters',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meters',
            name='unit_id',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
